fix keep_row_if for categorical indexes
pollandroll/daru_lite pull request #31
Opened 2024-09-02 15:28 UTC by thomasnaude

2024-09-02 15:30 UTC, thomasnaude commented
@Samuel-Labagnere

2024-09-03 10:40 UTC, max-las commented on lib/daru_lite/data_frame/filterable.rb
> +        end
- Les lignes sont maintenant parcourues dans l'ordre inverse de l'index, alors qu'avant elles étaient parcourues dans le bon ordre, faut-il s'en préoccuper ?
- `row_at` semble renvoyer la ligne sans son `name`, tandis qu'avant le `name` était inclus avec les lignes dans `keep_row_if`. On risque donc de casser les codebases où le `name` est utilisé dans `keep_row_if`

2024-09-03 10:40 UTC, max-las commented on lib/daru_lite/dataframe.rb
> +      raise IndexError, "Position #{position} does not exist." unless size - 1 >= position
`unless position < size` ?

2024-09-03 10:40 UTC, max-las commented on lib/daru_lite/dataframe.rb
> +    def delete_at_position(position)
De ce que je comprends, `delete_row` est déjà censé supporter aussi bien les index nommés que les index positionnels. Dans ce cas pourquoi ne pas modifier `delete_row` plutôt que de créer toutes ces méthodes ?

2024-09-03 10:40 UTC, max-las commented on lib/daru_lite/vector.rb
> +    def delete_at_position(position)
Quelle différence avec `delete_at` juste au-dessus ?

2024-09-03 12:01 UTC, thomasnaude commented on lib/daru_lite/dataframe.rb
> +    def delete_at_position(position)
delete_row ne fonction qu'avec un Index normal (non categorical)

2024-09-03 12:13 UTC, Samuel-Labagnere reviewed
Rien de plus à ajouter vis-à-vis des retours déjà faits par @max-las.

Si ce n'est appuyer sur la pertinence de l'indicateur `name` dans la méthode `keep_row_if`. C'est l'une des propriétés les plus explicites pour le filtrage des lignes, et il serait dommage de la perdre en passant par `row_at`. Ne faudrait-il pas rajouter la propriété `name` au nouveau vecteur retourné par cette méthode?

2024-09-03 14:27 UTC, thomasnaude commented on lib/daru_lite/data_frame/filterable.rb
> +        end
j'ai ajouté la variable name
Pour l'ordre inverse, je ne vois pas de contre-indication dans la mesure où l'on vient effectuer une vérification sur chaque ligne

2024-09-03 14:29 UTC, thomasnaude commented
@max-las

2024-09-03 14:34 UTC, max-las commented on lib/daru_lite/data_frame/filterable.rb
> +        end
Et si on utilise `keep_row_if.with_index` ?

2024-09-03 14:34 UTC, max-las commented on lib/daru_lite/dataframe.rb
> +    def delete_at_position(position)
Justement pourquoi ne pas corriger `delete_row` ?

2024-09-03 14:39 UTC, max-las commented on lib/daru_lite/data_frame/fetchable.rb
> +          DaruLite::Vector.new(row, index: @vectors, name: positions)
Le name sera donc la position ? Je pense que ce n'est pas le comportement actuel de `keep_row_if`

2024-09-04 08:26 UTC, max-las requested changes

2024-09-04 08:26 UTC, max-las commented on lib/daru_lite/index/index.rb
> +    end
Pour être cohérent avec Array#delete_at et même DaruLite::Vector#delete_at, ne faudrait-il pas rendre cette méthode destructive ? D'autant que les méthodes `delete_at_position` que tu as ajouté le sont

2024-09-04 08:26 UTC, max-las commented on lib/daru_lite/data_frame/fetchable.rb
> +          DaruLite::Vector.new(row, index: @vectors, name: positions)
Toujours d'actualité

2024-09-04 12:59 UTC, thomasnaude commented on lib/daru_lite/index/index.rb
> +    end
Aujourd'hui Index est immuable

2024-09-04 14:54 UTC, max-las requested changes

2024-09-04 14:54 UTC, max-las commented on lib/daru_lite/data_frame/fetchable.rb
> +            name: @name
Est-ce bien pertinent d'attribuer le nom de la dataframe source à celle qui résulte de `row_at` ? En tous cas ça ne répond à aucune issue actuelle

2024-09-05 13:10 UTC, thomasnaude commented on lib/daru_lite/data_frame/fetchable.rb
> +            name: @name
J'ai repris le fonctionnement de la méthode #at

2024-09-05 13:10 UTC, thomasnaude commented
@max-las

2024-09-05 13:37 UTC, max-las approved these changes

2024-09-05 13:40 UTC, merged