rotate_vectors of mixed classes
pollandroll/daru_lite pull request #33
Opened 2024-09-03 16:10 UTC by thomasnaude

2024-09-04 08:42 UTC, max-las requested changes
Ce problème avait déjà été relevé dans https://github.com/pollandroll/daru_lite/issues/21  et corrigé dans https://github.com/pollandroll/daru_lite/pull/22. Cette correction semble avoir été annulée dans fcceaf8, que s'est-il passé dans ce commit ? D'autres changements sont-ils passés à la trappe ?

2024-09-04 08:42 UTC, max-las commented on lib/daru_lite/data_frame/sortable.rb
> +          order_array.sort_by(&:to_s) == vectors.to_a.sort_by(&:to_s)
Dans #22 le check était fait avec `vectors.to_a.tally == order_array.tally`, ce qui me semble plus robuste

2024-09-04 14:48 UTC, max-las requested changes

2024-09-04 14:48 UTC, max-las commented on spec/data_frame/sortable_example.rb
> +        expect(subject.vectors.to_a).to eq(new_order)
Utiliser change ?

2024-09-05 13:11 UTC, thomasnaude commented
@max-las

2024-09-05 13:30 UTC, max-las approved these changes

2024-09-05 13:35 UTC, merged